CREATE TEMPORARY TABLE session_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  email VARCHAR(255) NOT NULL,
  email_lc VARCHAR(255) GENERATED ALWAYS AS (LOWER(email)) STORED,
  payload JSONB,
  created_at DATETIME DEFAULT NOW()
);

CREATE MATERIALIZED VIEW session_event_summary AS
SELECT email_lc, COUNT(*) AS event_count
FROM session_events
GROUP BY email_lc;

CREATE OR REPLACE FUNCTION normalize_email(text)
RETURNS text
LANGUAGE sql
AS 'select lower($1)';

CREATE SEQUENCE IF NOT EXISTS session_event_seq START 1;

ALTER TABLE session_events
  DROP CONSTRAINT IF EXISTS uq_session_events_email,
  ALTER COLUMN email SET NOT NULL,
  ALTER COLUMN created_at DROP DEFAULT,
  RENAME COLUMN email TO raw_email;

DROP MATERIALIZED VIEW IF EXISTS session_event_summary;
DROP FUNCTION IF EXISTS normalize_email;
DROP SEQUENCE IF EXISTS session_event_seq;
