-- migration: 20260529_add_billing_objects
BEGIN;

/* Create a billing table with generated data for lookup paths. */
CREATE TABLE IF NOT EXISTS billing_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  tenant_id BIGINT NOT NULL,
  payload JSONB NOT NULL,
  event_key VARCHAR(128) GENERATED ALWAYS AS (payload->>'event_key') STORED,
  created_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (id)
);

CREATE INDEX idx_billing_events_tenant_created
ON billing_events (tenant_id, created_at DESC);

CREATE OR REPLACE FUNCTION normalize_event_key(text)
RETURNS text
LANGUAGE sql
AS 'select lower($1)';

WITH recent AS (
  SELECT tenant_id, COUNT(*) AS cnt
  FROM billing_events
  WHERE created_at > NOW() - INTERVAL '7 days'
  GROUP BY tenant_id
)
SELECT tenant_id, cnt
FROM recent
ORDER BY cnt DESC NULLS LAST
LIMIT 25;

COMMIT;
