SELECT *
FROM orders
WHERE account_id = :account_id
  AND status = @status
  AND created_at >= $1
  AND total >= ?;

INSERT INTO orders (account_id, status, total, created_at)
VALUES (:account_id, @status, ?, NOW())
RETURNING id, account_id, status, total;

INSERT INTO orders (account_id, status, total, created_at)
VALUES :rows
RETURNING id, account_id, status, total;

INSERT INTO orders (account_id, status, total, created_at)
VALUES :row
RETURNING id, account_id, status, total;

INSERT INTO account_settings SET
  account_id = :account_id,
  retention_days = make_interval(days => :retention_days),
  updated_by = @actor
ON CONFLICT (account_id) DO UPDATE SET
  retention_days = make_interval(days := :retention_days),
  updated_by = @actor
RETURNING account_id, retention_days;

UPDATE orders
SET status = :next_status,
    total = total + :adjustment,
    metadata = jsonb_set(metadata, path => :json_path, value := ?)
WHERE account_id = :account_id
  AND id = $1
RETURNING id, status, total;

DELETE FROM orders
WHERE account_id = :account_id
  AND status = @deleted_status
  AND created_at < ?
RETURNING id;

SELECT make_interval(days => :days, hours := ?)
FROM system_settings
WHERE tenant_id = :tenant_id;

CALL refresh_account_cache(account_id => :account_id, force := ?);

CREATE TABLE IF NOT EXISTS param_defaults (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  account_id BIGINT NOT NULL DEFAULT :default_account_id CHECK (account_id <> :blocked_account_id),
  status VARCHAR(32) DEFAULT @default_status,
  status_lc VARCHAR(32) GENERATED ALWAYS AS (normalize_status(status => :default_status)) STORED,
  created_at DATETIME DEFAULT NOW() ON UPDATE COALESCE(:updated_at, NOW()),
  CONSTRAINT chk_param_defaults_status CHECK (status <> :invalid_status)
);

CREATE VIEW active_param_orders AS
SELECT id, account_id, status
FROM orders
WHERE account_id = :account_id
  AND status = @active_status;

CREATE MATERIALIZED VIEW active_param_order_totals AS
SELECT account_id, COUNT(*) AS order_count
FROM orders
WHERE account_id = :account_id
GROUP BY account_id;

CREATE TABLE param_order_snapshot AS
SELECT id, account_id, status, total
FROM orders
WHERE account_id = :account_id
  AND status = @snapshot_status;

CREATE INDEX idx_orders_account_status_param
ON orders (account_id, status);

ALTER TABLE param_defaults
  ADD COLUMN expires_at DATETIME DEFAULT :expires_at,
  ADD CONSTRAINT chk_param_defaults_account CHECK (account_id <> :blocked_account_id),
  ALTER COLUMN status SET DEFAULT :default_status,
  ALTER COLUMN account_id SET DEFAULT $1;

CREATE OR REPLACE FUNCTION normalize_status(text)
RETURNS text
LANGUAGE sql
AS 'select COALESCE(:status, $1)';

SHOW TABLES WHERE table_name = :table_name;

EXPLAIN SELECT id
FROM orders
WHERE account_id = :account_id
  AND status = @status;

TRUNCATE TABLE param_defaults;

DROP VIEW active_param_orders;
DROP MATERIALIZED VIEW IF EXISTS active_param_order_totals;
DROP FUNCTION IF EXISTS normalize_status;
